import type { Chair, ClinicConfig } from '../types/clinic';

export const DEFAULT_CHAIRS_PRESET: Record<number, Chair[]> = {
  1: [
    {
      id: 'chair-1',
      name: 'Primary Operatory',
      roomNumber: 'Room 101',
      status: 'occupied',
      currentPatientName: 'Eleanor Vance',
      assignedDoctorName: 'Dr. Sarah Jenkins',
      currentProcedure: 'Root Canal Therapy #14',
      nextAppointmentTime: '11:30 AM',
    },
  ],
  2: [
    {
      id: 'chair-1',
      name: 'Operatory 1 (Hygiene)',
      roomNumber: 'Room 101',
      status: 'occupied',
      currentPatientName: 'Eleanor Vance',
      assignedDoctorName: 'Dr. Sarah Jenkins',
      currentProcedure: 'Crown Preparation #19',
      nextAppointmentTime: '11:30 AM',
    },
    {
      id: 'chair-2',
      name: 'Operatory 2 (Surgery)',
      roomNumber: 'Room 102',
      status: 'available',
      nextAppointmentTime: '11:00 AM',
    },
  ],
  5: [
    {
      id: 'chair-1',
      name: 'Operatory 1',
      roomNumber: 'Room 101',
      status: 'occupied',
      currentPatientName: 'Eleanor Vance',
      assignedDoctorName: 'Dr. Sarah Jenkins',
      currentProcedure: 'Root Canal #14',
      nextAppointmentTime: '11:30 AM',
    },
    {
      id: 'chair-2',
      name: 'Operatory 2',
      roomNumber: 'Room 102',
      status: 'available',
      nextAppointmentTime: '11:00 AM',
    },
    {
      id: 'chair-3',
      name: 'Operatory 3 (Hygiene)',
      roomNumber: 'Room 103',
      status: 'occupied',
      currentPatientName: 'Marcus Aurelius',
      assignedDoctorName: 'RDH Chloe Bennett',
      currentProcedure: 'Full Mouth Prophylaxis',
      nextAppointmentTime: '11:15 AM',
    },
    {
      id: 'chair-4',
      name: 'Operatory 4 (Pediatric)',
      roomNumber: 'Room 104',
      status: 'cleaning',
      nextAppointmentTime: '11:45 AM',
    },
    {
      id: 'chair-5',
      name: 'Operatory 5 (Orthodontics)',
      roomNumber: 'Room 105',
      status: 'maintenance',
      nextAppointmentTime: '02:00 PM',
    },
  ],
  10: [
    {
      id: 'chair-1',
      name: 'Chair 1 - Surgery A',
      roomNumber: 'Room 101',
      status: 'occupied',
      currentPatientName: 'Eleanor Vance',
      assignedDoctorName: 'Dr. Sarah Jenkins',
      currentProcedure: 'Implants Placement #30',
      nextAppointmentTime: '11:30 AM',
    },
    {
      id: 'chair-2',
      name: 'Chair 2 - Surgery B',
      roomNumber: 'Room 102',
      status: 'available',
      nextAppointmentTime: '11:00 AM',
    },
    {
      id: 'chair-3',
      name: 'Chair 3 - Hygiene A',
      roomNumber: 'Room 103',
      status: 'occupied',
      currentPatientName: 'Marcus Aurelius',
      assignedDoctorName: 'RDH Chloe Bennett',
      currentProcedure: 'Prophylaxis',
      nextAppointmentTime: '11:15 AM',
    },
    {
      id: 'chair-4',
      name: 'Chair 4 - Hygiene B',
      roomNumber: 'Room 104',
      status: 'cleaning',
      nextAppointmentTime: '11:45 AM',
    },
    {
      id: 'chair-5',
      name: 'Chair 5 - Ortho A',
      roomNumber: 'Room 105',
      status: 'available',
      nextAppointmentTime: '11:30 AM',
    },
    {
      id: 'chair-6',
      name: 'Chair 6 - Ortho B',
      roomNumber: 'Room 106',
      status: 'occupied',
      currentPatientName: 'Sophia Loren',
      assignedDoctorName: 'Dr. Michael Chang',
      currentProcedure: 'Aligner Check',
      nextAppointmentTime: '12:00 PM',
    },
    {
      id: 'chair-7',
      name: 'Chair 7 - Restorative',
      roomNumber: 'Room 107',
      status: 'available',
      nextAppointmentTime: '01:00 PM',
    },
    {
      id: 'chair-8',
      name: 'Chair 8 - Endodontics',
      roomNumber: 'Room 108',
      status: 'maintenance',
      nextAppointmentTime: '02:30 PM',
    },
    {
      id: 'chair-9',
      name: 'Chair 9 - General',
      roomNumber: 'Room 109',
      status: 'cleaning',
      nextAppointmentTime: '11:50 AM',
    },
    {
      id: 'chair-10',
      name: 'Chair 10 - VIP Suite',
      roomNumber: 'Room 110',
      status: 'occupied',
      currentPatientName: 'Alexander Hamilton',
      assignedDoctorName: 'Dr. Sarah Jenkins',
      currentProcedure: 'Veneers Consultation',
      nextAppointmentTime: '01:15 PM',
    },
  ],
};

export const INITIAL_CLINIC_CONFIG: ClinicConfig = {
  id: 'dentova-main-clinic',
  name: 'Dentova Dental Suites',
  chairCount: 5,
  chairs: DEFAULT_CHAIRS_PRESET[5],
  activeChairId: 'chair-1',
  taxId: 'TX-9948201',
  address: '742 Evergreen Terrace, Suite 400, Dental Plaza',
  phone: '+1 (555) 234-5678',
  email: 'contact@dentovasuites.com',
};
