"use client";

import { useEffect, useState } from "react";
import { Activity, Armchair, ArrowDownWideNarrow, ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, Clock3, Ellipsis, Heart, MoreHorizontal, Plus, RefreshCw, Search, Settings2, Sparkles, Users, X } from "lucide-react";
import { Avatar, DentalChair, EmptyState, StatusBadge, Tooth } from "@/components/ui";
import { queueFor, useClinic } from "@/components/clinic-context";
import { DOCTORS, initials, timeLabel, todayISO, type Chair } from "@/lib/types";

export function Metrics() {
  const { data, now } = useClinic();
  const queue = queueFor(data);
  const today = data.visits.filter(v => v.date === todayISO() && v.status !== "cancelled");
  const occupied = data.chairs.filter(c => c.status === "in_treatment").length;
  const wait = queue.length ? Math.round(queue.reduce((sum, v) => sum + Math.max(0, (now - new Date(v.checkedInAt ?? now).getTime()) / 60000), 0) / queue.length) : 0;
  const metrics = [
    { label: "Today’s appointments", value: String(today.length).padStart(2, "0"), detail: `${today.filter(v => v.status === "completed").length} completed today`, icon: CalendarDays, color: "lavender", mini: "appointments" },
    { label: "In waiting room", value: String(queue.length).padStart(2, "0"), detail: "A warm welcome, a shorter wait", icon: Users, color: "amber", mini: "waiting" },
    { label: "In treatment", value: String(occupied).padStart(2, "0"), detail: `${data.chairs.length - occupied} ${data.chairs.length - occupied === 1 ? "chair" : "chairs"} not in treatment`, icon: Armchair, color: "blue", mini: "treatment" },
    { label: "Average wait time", value: String(wait).padStart(2, "0"), detail: wait <= 15 ? "Keeping your day flowing" : "A little update goes a long way", icon: Clock3, color: "sage", mini: "time", suffix: "min" },
  ];
  return <div className="metrics-grid">{metrics.map(({ label, value, detail, icon: Icon, color, suffix, mini }) => <section className={`metric-card metric-${color}`} key={label} aria-label={`${label}: ${value}${suffix ?? ""}`}><div className="metric-copy"><span className="metric-label">{label}</span><div className="metric-value">{value}{suffix && <span>{suffix}</span>}<span className={`metric-signal signal-${mini}`} aria-hidden="true">{mini === "appointments" ? <svg viewBox="0 0 70 28"><path d="m2 23 10-6 9 3 10-12 8 4 11-8 8 3 10-6"/></svg> : mini === "waiting" ? <><i/><i/><i/><i/><i/></> : mini === "treatment" ? <><i/><i/><i/></> : <svg viewBox="0 0 70 28"><path d="m2 7 10 4 8-2 10 9 10-4 10 6 8-3 10 5"/></svg>}</span></div><span className="metric-detail">{mini === "appointments" && <CheckCheck size={12}/>} {detail}</span></div><span className={`metric-icon ${color}`}><Icon size={20} strokeWidth={1.6}/></span></section>)}</div>;
}

export function WaitingRoom() {
  const { data, openDialog } = useClinic();
  const [chairFilter, setChairFilter] = useState("all");
  const visibleChairs = data.chairs.filter(c => chairFilter === "all" || c.status === chairFilter);
  return <><nav className="flow-switcher" aria-label="Waiting room quick navigation"><a href="#clinic-chairs"><Armchair size={15}/> Chairs <span>{data.chairs.length}</span></a><a href="#waiting-queue"><Users size={15}/> Waiting queue <span>{queueFor(data).length}</span><ArrowRight size={14}/></a></nav><section className="chairs-section" id="clinic-chairs"><div className="section-heading"><div className="section-title"><h2>Dental chairs</h2><span className="count-pill">{data.chairs.length.toString().padStart(2, "0")}</span></div><div className="chair-section-actions"><div className="chair-legend" aria-label="Filter chair status">{[{ status: "available", label: "Available" }, { status: "in_treatment", label: "In treatment" }, { status: "cleaning", label: "Cleaning" }].map(item => <button key={item.status} className={`legend-item ${chairFilter === item.status ? "legend-selected" : ""}`} onClick={() => setChairFilter(chairFilter === item.status ? "all" : item.status)} aria-pressed={chairFilter === item.status}><span className={`legend-dot legend-${item.status}`}/>{item.label}</button>)}</div><span className="section-divider"/><button className="text-button manage-chairs" onClick={() => openDialog({ type: "chairs" })}><Settings2 size={14}/> Manage chairs</button></div></div><div className={`chairs-grid ${data.chairs.length > 5 ? "chairs-grid-dense" : ""}`}>{visibleChairs.map(chair => <ChairCard key={chair.id} chair={chair}/>)}</div>{!visibleChairs.length && <div className="card"><EmptyState title={`No chairs ${chairFilter === "cleaning" ? "being cleaned" : chairFilter === "available" ? "available right now" : "in treatment"}`} description="Choose another status to see the rest of your chairs." action={<button className="button button-white" onClick={() => setChairFilter("all")}>Show all chairs</button>}/></div>}</section><div className="waiting-layout"><Queue/><div className="right-rail"><Schedule/><FollowUpTip/></div></div></>;
}

function ChairCard({ chair }: { chair: Chair }) {
  const { data, now, openDialog, busy, mutate } = useClinic();
  const patient = data.patients.find(p => p.id === chair.patientId);
  const visit = data.visits.find(v => v.patientId === chair.patientId && v.status === "in_treatment");
  const next = queueFor(data)[0];
  const elapsed = chair.startedAt ? Math.max(0, Math.floor((now - new Date(chair.startedAt).getTime()) / 60000)) : 0;
  return <article className={`chair-card chair-${chair.status}`}><div className="chair-card-header"><h3><Armchair size={17} strokeWidth={1.65}/>{chair.name}</h3><StatusBadge status={chair.status}/></div>{chair.status === "in_treatment" && patient ? <><button className="chair-patient" onClick={() => openDialog({ type: "patient", patientId: patient.id })}><Avatar name={patient.name} color={patient.color}/><span><strong>{patient.name}</strong><small>{chair.treatment}</small></span><ArrowUpRight size={15}/></button><div className="treatment-timing"><div><span><Clock3 size={12}/>{elapsed} min elapsed</span><span>{visit?.duration ?? 30} min session</span></div><div className="treatment-progress"><span style={{ width: `${Math.min(100, elapsed / (visit?.duration ?? 30) * 100)}%` }}/></div></div><div className="chair-footer"><span className="chair-doctor"><Avatar name={chair.doctor} color={chair.doctor.includes("Daniel") ? "blue" : "lavender"} small/>{chair.doctor}</span><button className="text-button" onClick={() => openDialog({ type: "chair", chairId: chair.id })}>View details <ArrowRight size={13}/></button></div></> : chair.status === "available" ? <><div className="available-body"><DentalChair size={72}/><div><strong>Ready for the next smile</strong><span>Clean, prepped, and all set.</span></div></div><button className="button call-next-button" disabled={!next || busy} onClick={() => openDialog({ type: "assign", chairId: chair.id, visitId: next?.id })}><span>{next ? "Call next patient" : "All caught up"}</span>{next ? <ArrowRight size={15}/> : <Check size={15}/>}</button></> : <><div className="available-body cleaning-body"><Sparkles size={42} strokeWidth={1.3}/><div><strong>A little refresh in progress</strong><span>Preparing for the next patient.</span></div></div><button className="button cleaning-button" disabled={busy} onClick={() => void mutate({ action: "ready", chairId: chair.id })}><Check size={15}/> Mark as ready</button></>}</article>;
}

function Queue() {
  const { data, now, openDialog, mutate, refresh, notify, offline, busy } = useClinic();
  const queue = queueFor(data);
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);
  const [sortByAppointment, setSortByAppointment] = useState(false);
  const [menu, setMenu] = useState<number | null>(null);
  useEffect(() => {
    if (menu === null) return;
    const close = (e: MouseEvent) => { if (!(e.target as HTMLElement).closest("[data-queue-menu]")) setMenu(null); };
    const escape = (e: KeyboardEvent) => { if (e.key === "Escape") setMenu(null); };
    document.addEventListener("mousedown", close); document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", escape); };
  }, [menu]);
  let filtered = queue.filter(v => (filter === "all" || v.kind === filter) && `${data.patients.find(p => p.id === v.patientId)?.name} ${v.treatment}`.toLowerCase().includes(query.toLowerCase()));
  if (sortByAppointment) filtered = [...filtered].sort((a, b) => a.time.localeCompare(b.time));
  const available = data.chairs.some(c => c.status === "available");
  return <section className="card queue-card" id="waiting-queue"><div className="card-header queue-heading"><div className="section-title"><h2>Waiting queue</h2><span className="count-pill count-purple">{queue.length.toString().padStart(2, "0")}</span></div><div className="queue-tools"><button className={`icon-button ${searchOpen ? "is-active" : ""}`} aria-label="Search waiting queue" onClick={() => { setSearchOpen(!searchOpen); setQuery(""); }}><Search size={17}/></button><button className={`icon-button ${sortByAppointment ? "is-active" : ""}`} aria-label={sortByAppointment ? "Sort by arrival time" : "Sort by appointment time"} title={sortByAppointment ? "Sorted by appointment time" : "Sorted by arrival time"} onClick={() => setSortByAppointment(!sortByAppointment)}><ArrowDownWideNarrow size={17}/></button></div></div><div className="queue-tabs-row"><div className="tabs queue-tabs">{[{ label: "All patients", value: "all" }, { label: "Scheduled", value: "scheduled" }, { label: "Walk-ins", value: "walk-in" }].map(tab => <button key={tab.value} className={`tab ${filter === tab.value ? "tab-active" : ""}`} onClick={() => setFilter(tab.value)} aria-pressed={filter === tab.value}>{tab.label}<span>{tab.value === "all" ? queue.length : queue.filter(v => v.kind === tab.value).length}</span></button>)}</div>{sortByAppointment && <span className="sort-label">By appointment</span>}</div>{searchOpen && <div className="queue-search"><Search size={16}/><input autoFocus placeholder="Find a waiting patient..." value={query} onChange={e => setQuery(e.target.value)} aria-label="Search waiting patients"/><button className="icon-button" aria-label="Close queue search" onClick={() => { setSearchOpen(false); setQuery(""); }}><X size={14}/></button></div>}<div className="queue-table-wrap"><table className="queue-table"><thead><tr><th>Patient</th><th>Appointment</th><th>Wait time</th><th className="action-heading">Action</th></tr></thead><tbody>{filtered.map(visit => {
    const patient = data.patients.find(p => p.id === visit.patientId)!;
    const isNext = visit.id === queue[0]?.id;
    const wait = Math.max(0, Math.floor((now - new Date(visit.checkedInAt ?? now).getTime()) / 60000));
    return <tr key={visit.id} className={isNext ? "next-patient-row" : ""}><td><button className="table-patient" onClick={() => openDialog({ type: "patient", patientId: patient.id })}><Avatar name={patient.name} color={patient.color}/><span><span className="patient-name-line"><strong>{patient.name}</strong>{isNext && <span className="next-badge">UP NEXT</span>}</span><small>{patient.age} years <i>·</i> {patient.gender}</small></span></button></td><td><div className="appointment-cell"><strong>{visit.treatment}</strong><small>{timeLabel(visit.time)}<i>·</i>{visit.kind === "walk-in" ? <span className="walk-in-label">Walk-in</span> : "Scheduled"}</small></div></td><td><span className={`wait-time ${wait >= 10 ? "wait-time-long" : ""}`}><Clock3 size={13}/>{wait} min</span></td><td><div className="queue-row-actions"><button className={`button assign-button ${isNext ? "button-primary" : "button-white"}`} onClick={() => openDialog({ type: "assign", visitId: visit.id })} disabled={busy || !available} title={available ? `Assign ${patient.name} to a chair` : "No chairs are available yet"}>Assign<ArrowRight size={12}/></button><div className="queue-menu-wrap" data-queue-menu><button className="icon-button row-more" aria-label={`More actions for ${patient.name}`} onClick={() => setMenu(menu === visit.id ? null : visit.id)} aria-expanded={menu === visit.id}><MoreHorizontal size={17}/></button>{menu === visit.id && <div className="popover queue-menu"><button onClick={() => { setMenu(null); openDialog({ type: "patient", patientId: patient.id }); }}><Users size={14}/> View patient</button>{!isNext && <button onClick={() => { setMenu(null); void mutate({ action: "queue-priority", visitId: visit.id }); }}><ArrowUpRight size={14}/> Move to front</button>}<button className="danger-text" onClick={() => { setMenu(null); openDialog({ type: "confirm", title: "Remove from waiting queue?", description: `${patient.name} will be removed from the queue. Their patient record will stay in your clinic.`, confirmLabel: "Remove patient", mutation: { action: "queue-remove", visitId: visit.id } }); }}><X size={14}/> Remove from queue</button></div>}</div></div></td></tr>;
  })}</tbody></table>{!filtered.length && <EmptyState title={query || filter !== "all" ? "No matching patients" : "A calm moment in your clinic"} description={query || filter !== "all" ? "Try another name or choose a different queue filter." : "Everyone has been seen. Check in a patient when they arrive."} action={!queue.length ? <button className="button button-white" onClick={() => openDialog({ type: "checkin" })}><Plus size={15}/> Check in patient</button> : undefined}/>}</div><div className="queue-footer"><span>Showing {filtered.length} of {queue.length} patients</span><button onClick={async () => { const ok = await refresh(); notify(ok ? "Your waiting room is up to date." : "Unable to refresh. We’ll keep trying.", !ok); }} className="queue-live" aria-label="Refresh waiting room"><span className={`live-dot ${offline ? "live-dot-warning" : ""}`}/>{offline ? "Reconnecting" : "Live updates"}<RefreshCw size={11}/></button></div></section>;
}

export function Schedule() {
  const { data, navigate, openDialog, setDate } = useClinic();
  const schedule = data.visits.filter(v => v.date === todayISO() && ["upcoming", "waiting"].includes(v.status));
  const preview = schedule.slice(0, 3);
  return <section className="card schedule-card"><div className="card-header"><h2>Today’s schedule</h2><span className="schedule-heading-icon"><CalendarDays size={17} strokeWidth={1.7}/></span></div><div className="schedule-list">{preview.length ? preview.map((visit, index) => {
    const patient = data.patients.find(p => p.id === visit.patientId)!;
    return <button className={`schedule-row ${index === 0 ? "schedule-row-next" : ""}`} key={visit.id} onClick={() => openDialog({ type: "patient", patientId: patient.id })}><span className="schedule-time">{timeLabel(visit.time).split(" ")[0]}<small>{timeLabel(visit.time).split(" ")[1]}</small></span><span className="schedule-timeline"><i/></span><span className="schedule-info"><strong>{patient.name}<span className={visit.status === "waiting" ? "tiny-dot green-dot" : "tiny-dot purple-dot"}/></strong><span>{visit.treatment}</span><small>{visit.doctor}</small></span></button>;
  }) : <EmptyState title="All done for today" description="A day of healthier smiles."/>}</div><button className="schedule-link" onClick={() => { setDate(todayISO()); navigate("Appointments"); }}>View full schedule <ArrowRight size={14}/></button></section>;
}

function FollowUpTip() {
  const { navigate } = useClinic();
  return <aside className="followup-tip"><div className="tip-decoration" aria-hidden="true"><Tooth size={69}/><Sparkles size={15}/><span>+</span></div><span className="tip-eyebrow"><Heart size={12}/> THE LITTLE THINGS MATTER</span><h3>Great care goes beyond the chair.</h3><p>A thoughtful follow-up can make their day.</p><button onClick={() => navigate("Follow-ups")}>Manage follow-ups <ArrowRight size={14}/></button></aside>;
}

export function Overview() {
  const { data, navigate, openDialog, now } = useClinic();
  return <div className="overview-layout"><div className="overview-main"><section className="card overview-chairs"><div className="card-header"><h2>Your clinic, at a glance</h2><button className="text-button" onClick={() => navigate("Waiting room")}>Open waiting room <ArrowRight size={14}/></button></div><div className="overview-chair-grid">{data.chairs.map(chair => <button className={`overview-chair overview-chair-${chair.status}`} key={chair.id} onClick={() => chair.status === "in_treatment" ? openDialog({ type: "chair", chairId: chair.id }) : navigate("Waiting room")}><DentalChair size={56}/><strong>{chair.name}</strong><StatusBadge status={chair.status}/></button>)}</div></section><section className="card activity-card"><div className="card-header"><h2>The rhythm of your day</h2><span className="subtle-label">Recent activity</span></div><div className="activity-list">{data.activity.slice(0, 7).map((item, index) => <div className="activity-item" key={item.id}><span className={`activity-icon ${index === 0 ? "lavender" : "sage"}`}>{index === 0 ? <Activity size={17}/> : <Check size={17}/>}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{Math.max(0, Math.floor((now - new Date(item.createdAt).getTime()) / 60000))}m ago</time></div>)}</div></section></div><div className="right-rail"><Schedule/><section className="card team-card"><div className="card-header"><h2>Your care team</h2><span className="count-pill">03</span></div>{DOCTORS.map((doctor, i) => <div className="team-member" key={doctor}><Avatar name={doctor} color={["lavender", "blue", "peach"][i]}/><div><strong>{doctor}</strong><small>{i === 0 ? "General & restorative" : i === 1 ? "General dentistry" : "Cosmetic dentistry"}</small></div><span className="live-dot"/></div>)}</section></div></div>;
}
